server:
 port: 8082
 
spring:
 application:
  name: MovieService
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    hostname: localhost
  